import { useEffect, useRef, useState } from "react";
import { ArrowUp, Bot, Check, Copy, Globe2, Image, Menu, MessageSquarePlus, Paperclip, Settings, Sparkles, Trash2, User, Video, X, Zap } from "lucide-react";
import "./nova.css";

const starters = [
  ["Plan a safer community", "Create a practical public-safety awareness plan for my neighborhood."],
  ["Analyze an image", "I will attach an image. Describe what is visible and flag possible safety concerns without guessing."],
  ["Create an image", "Create a clear public-safety poster about emergency preparedness."],
  ["Explain anything", "Explain a difficult topic clearly, with examples and uncertainty where appropriate."],
];

function ChatMessage({ item }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => { await navigator.clipboard.writeText(item.content); setCopied(true); setTimeout(() => setCopied(false), 1200); };
  return <div className={`message-row ${item.role}`}><div className="avatar">{item.role === "assistant" ? <Sparkles size={17} /> : <User size={17} />}</div><div className="message-body"><b>{item.role === "assistant" ? "Nova" : "You"}</b><div className="message-content">{item.image && <img className="generated-image" src={item.image} alt="Generated by Nova" />}{item.content}</div>{item.role === "assistant" && <button className="copy-button" onClick={copy}>{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? "Copied" : "Copy"}</button>}</div></div>;
}

export default function NovaApp() {
  const [messages, setMessages] = useState(() => JSON.parse(localStorage.getItem("nova-chat") || "[]"));
  const [input, setInput] = useState(""); const [loading, setLoading] = useState(false); const [sidebar, setSidebar] = useState(true);
  const [webSearch, setWebSearch] = useState(true); const [attachments, setAttachments] = useState([]); const [mode, setMode] = useState("chat"); const [settingsOpen, setSettingsOpen] = useState(false);
  const [prefs, setPrefs] = useState(() => JSON.parse(localStorage.getItem("nova-settings") || '{"theme":"light","saveHistory":true,"compact":false}'));
  const fileRef = useRef(null); const endRef = useRef(null);
  useEffect(() => endRef.current?.scrollIntoView({ behavior: "smooth" }), [messages, loading]);
  useEffect(() => { localStorage.setItem("nova-settings", JSON.stringify(prefs)); document.documentElement.dataset.theme = prefs.theme; if (prefs.saveHistory) localStorage.setItem("nova-chat", JSON.stringify(messages)); else localStorage.removeItem("nova-chat"); }, [prefs, messages]);

  const reset = () => { setMessages([]); setInput(""); setAttachments([]); localStorage.removeItem("nova-chat"); };
  const addFiles = async (list) => {
    const files = [...list].filter((file) => file.size <= 10 * 1024 * 1024).slice(0, 5 - attachments.length);
    const encoded = await Promise.all(files.map((file) => new Promise((resolve) => { const reader = new FileReader(); reader.onload = () => resolve({ name: file.name, mime: file.type, data: reader.result }); reader.readAsDataURL(file); })));
    setAttachments((value) => [...value, ...encoded]);
  };
  const send = async (prompt = input) => {
    const text = prompt.trim(); if (!text || loading) return;
    const next = [...messages, { role: "user", content: text }]; setMessages(next); setInput(""); setLoading(true);
    try {
      const endpoint = mode === "chat" ? "/api/chat" : `/api/generate/${mode}`;
      const payload = mode === "chat" ? { messages: next.map(({ role, content }) => ({ role, content })), web_search: webSearch, attachments } : { prompt: text };
      const response = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json();
      if (!response.ok) throw new Error(data.message || "The request could not be completed.");
      const answer = mode === "image" ? { role: "assistant", content: "Your image is ready.", image: data.image } : mode === "video" ? { role: "assistant", content: `Video job ${data.id} is ${data.status}. ${data.warning || ""}` } : { role: "assistant", content: data.answer };
      setMessages([...next, answer]); setAttachments([]);
    } catch (error) { setMessages([...next, { role: "assistant", content: `I could not complete that request. ${error.message}` }]); } finally { setLoading(false); }
  };

  return <div className={`nova-shell ${prefs.compact ? "compact" : ""}`}>
    <aside className={`sidebar ${sidebar ? "open" : ""}`}><div className="brand"><span className="brand-mark"><Sparkles size={20} /></span>nova<span>.ai</span></div><button className="new-chat" onClick={reset}><MessageSquarePlus size={18} /> New conversation</button><small>Today</small><div className="history-item"><Bot size={16} /> Current conversation</div><div className="sidebar-spacer" /><div className="pro-card"><Zap size={17} /><b>Safety-first intelligence</b><p>Private by design, useful by default.</p></div><button className="side-action" onClick={() => setSettingsOpen(true)}><Settings size={17} /> Settings</button><button className="side-action" onClick={reset}><Trash2 size={17} /> Clear chat</button></aside>
    <main className="workspace"><header><button onClick={() => setSidebar(!sidebar)}><Menu size={20} /></button><div><b>Nova Assistant</b><span><i /> Online</span></div><button className={`web-toggle ${webSearch ? "on" : ""}`} onClick={() => setWebSearch(!webSearch)}><Globe2 size={16} /> Web {webSearch ? "on" : "off"}</button></header>
      <section className="conversation">{messages.length === 0 ? <div className="welcome"><div className="orb"><Sparkles size={34} /></div><p className="eyebrow">Meet Nova</p><h1>Share, create, and<br /><span>understand anything.</span></h1><p className="subtitle">Talk with AI, analyze images and documents, create visuals, and get clear help—with privacy and responsible guidance built in.</p><div className="starter-grid">{starters.map(([title, prompt]) => <button key={title} onClick={() => send(prompt)}><Sparkles size={17} /><div><b>{title}</b><p>{prompt}</p></div></button>)}</div></div> : <div className="messages">{messages.map((item, index) => <ChatMessage key={index} item={item} />)}{loading && <div className="thinking">Nova is thinking <i /><i /><i /></div>}<div ref={endRef} /></div>}</section>
      <div className="composer-wrap">{attachments.length > 0 && <div className="attachments">{attachments.map((file, i) => <span key={`${file.name}-${i}`}><Paperclip size={13} />{file.name}<button onClick={() => setAttachments(attachments.filter((_, index) => i !== index))}><X size={12} /></button></span>)}</div>}<div className="mode-row"><button className={mode === "chat" ? "active" : ""} onClick={() => setMode("chat")}><Sparkles size={14} /> Chat</button><button className={mode === "image" ? "active" : ""} onClick={() => setMode("image")}><Image size={14} /> Image</button><button className={mode === "video" ? "active" : ""} onClick={() => setMode("video")}><Video size={14} /> Video</button></div><div className="composer"><input ref={fileRef} hidden type="file" multiple accept="image/*,.pdf,.txt,.md,.csv" onChange={(e) => addFiles(e.target.files)} /><button className="attach" onClick={() => fileRef.current?.click()}><Paperclip size={19} /></button><textarea rows="1" value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder={mode === "chat" ? "Message Nova or attach a file..." : `Describe the ${mode} you want...`} /><button className="send" onClick={() => send()} disabled={!input.trim() || loading}><ArrowUp size={20} /></button></div><p>Nova can make mistakes. Verify important information. Maximum 5 files, 10 MB each.</p></div>
    </main>
    {settingsOpen && <div className="modal" onClick={() => setSettingsOpen(false)}><section className="settings-panel" onClick={(e) => e.stopPropagation()}><div className="settings-head"><div><small>Personalize Nova</small><h2>Settings</h2></div><button onClick={() => setSettingsOpen(false)}><X /></button></div><label><span><b>Appearance</b><small>Choose your preferred interface theme.</small></span><select value={prefs.theme} onChange={(e) => setPrefs({ ...prefs, theme: e.target.value })}><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span><b>Search the web</b><small>Use live sources for current questions.</small></span><input type="checkbox" checked={webSearch} onChange={(e) => setWebSearch(e.target.checked)} /></label><label><span><b>Save history</b><small>Store conversations only in this browser.</small></span><input type="checkbox" checked={prefs.saveHistory} onChange={(e) => setPrefs({ ...prefs, saveHistory: e.target.checked })} /></label><label><span><b>Compact mode</b><small>Show more conversation on screen.</small></span><input type="checkbox" checked={prefs.compact} onChange={(e) => setPrefs({ ...prefs, compact: e.target.checked })} /></label><div className="privacy-note"><b>Privacy & safety</b><p>Your API key remains on the server. Nova does not request API response storage. Never share passwords, payment credentials, or highly sensitive personal data.</p></div></section></div>}
  </div>;
}
